### ISSUE TITLE
Expressions Evaluator package requires authentication

### ISSUE THREAD

**Issue by flixlo** [azamat-murzagalin/k-x-v#2]
Hi again @murzagalin!

After trying to add your library to my kotlin multiplatform project, the gradle build failed with an error. So I tried to setup a new empty test project (via the project wizard of Android Studio) to verify that my configuration is not responsible for the error. 

I tested with a new `Kotlin Multiplatform Library` and a `Kotlin Multiplatform App` project. In both cases, I added your library as suggested in the README.

```kotlin
    repositories {
        maven {
            url = uri("https://maven.pkg.github.com/murzagalin/multiplatform-expressions-evaluator")
        }
    }

    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation("com.github.murzagalin:multiplatform-expressions-evaluator:0.11.0")
            }
        }
        // other stuff ...
    }
```

Building the project gives the following error in both cases
```
Could not GET 'https://maven.pkg.github.com/murzagalin/multiplatform-expressions-evaluator/com/github/murzagalin/multiplatform-expressions-evaluator/0.11.0/multiplatform-expressions-evaluator-0.11.0.pom'. Received status code 401 from server: Unauthorized
Disable Gradle 'offline mode' and sync project
```
Manually trying to access https://maven.pkg.github.com/murzagalin/multiplatform-expressions-evaluator/com/github/murzagalin/multiplatform-expressions-evaluator/0.11.0/multiplatform-expressions-evaluator-0.11.0.pom also requires authentication.

It appears that the Github Package is private. Is that intended, or is it possible to make it publicly accessible without authentication?

**Comment by murzagalin** [comment]
Let me check if I can make it public

**Comment by murzagalin** [comment]
I did the investigation. Unfortunately github packages does not support unauthenticated access to packages.
To access the package you will have to create your own access token: https://docs.github.com/en/enterprise-server@3.4/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

make sure you select `read:packages` permission for the token 
![image](https://user-images.githubusercontent.com/3996377/182615379-d293aaba-784b-4d16-9b70-f268d5641034.png)

and change repository part to 
```kotlin
    maven {
        url = uri("https://maven.pkg.github.com/murzagalin/multiplatform-expressions-evaluator")
        credentials {
            username = "your username"
            password = "your token"
        }
    }
```

**Comment by murzagalin** [comment]
I will change the docs after your confirmation

**Comment by flixlo** [comment]
Ah, I haven't used Github Packages before, and didn't know that it always requires authentication. Adding a hint to the README seems like a good idea :)

I created the PAT with the correct permissions, but I'm still struggeling to make it work. This is what my gradle.kts looks like:

```kotlin
kotlin {
    android()
    iosX64()
    iosArm64()
    iosSimulatorArm64()

    repositories {
        maven {
            url = uri("https://maven.pkg.github.com/murzagalin/multiplatform-expressions-evaluator")
            credentials {
                username = "flixlo"
                password = "ghp_xxx"
            }
        }
    }

    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation("com.github.murzagalin:multiplatform-expressions-evaluator:0.11.0")
            }
        }
        // ...
    }
}
```

Yet, I get the following error:
```
Could not resolve com.github.murzagalin:multiplatform-expressions-evaluator:0.11.0.
Required by:
    project :shared

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

Directly accessing the .pom with my username and PAT works properly: https://maven.pkg.github.com/murzagalin/multiplatform-expressions-evaluator/com/github/murzagalin/multiplatform-expressions-evaluator/0.11.0/multiplatform-expressions-evaluator-0.11.0.pom

**Comment by murzagalin** [comment]
I tested it locally in a kmp project. It seems you are adding the repositories block to a wrong place.
Please add it outside of `kotlin` block, with other repositories.

I also have couple of questions:
How many modules do you have in the project?
And what is your module structure?

I experienced the same issue, until I added the repo to all modules that required it. In your case it is `:shared`

**Comment by flixlo** [comment]
I tried different places, even in `allprojects { repositories { /*...*/ } }`, but I'm still getting the same error.

If it works for you, do you mind sharing your gradle files, or even the whole test-project, so I can compare what I'm doing different?

**Comment by murzagalin** [comment]
I did the investigation. I could reproduce the problem. Check [this repo](https://github.com/murzagalin/expressions-evaluator-test)

and the problem happened because of [`iosSimulatorArm64()`](https://github.com/murzagalin/expressions-evaluator-test/blob/f1eae14c6b2fb813b82d67a8258922e933082d60/shared/build.gradle.kts#L13) target. When I commented it, everything started working. Is it sth critical?

**Comment by flixlo** [comment]
@murzagalin Thx for the investigation, I can reproduce that.

What surprised me: If I switch to `publishToMavenLocal` and `implementation("com.github.murzagalin:multiplatform-expressions-evaluator:local")`, the local build works properly with my app (that's why I previously created the PR), while the production version of the lib does not (as explained above). When setting up a new empty kmm app project (as you did in the test repo), the error persists - even with the local build of the lib. I guess the configuration of my app differs from the test project, I will check that later.

Using `iosSimulatorArm64()` would be important to me, can you please confirm the following: 

Change the configuration of `multiplatform-expressions-evaluator` from 
```kotlin
    ios {
        binaries {
            framework {
                baseName = "ExpressionsEvaluator"
            }
        }
    }
```
to
```kotlin
    iosX64()
    iosArm64()
    iosSimulatorArm64()
```

I tried this locally, and it seems to work with the test project.

**Comment by murzagalin** [comment]
could you open a PR with these changes?

**Comment by murzagalin** [comment]
or I will create a PR!

**Comment by murzagalin** [comment]
could you check and approve if this is what you meant https://github.com/murzagalin/multiplatform-expressions-evaluator/pull/3

**Comment by murzagalin** [comment]
could you try version `0.13.0`, @flixlo

**Comment by flixlo** [comment]
It works now, thank you :)
