### ISSUE TITLE
Distribution via Maven Central

### ISSUE THREAD

**Issue by flixlo** [azamat-murzagalin/k-x-v#4]
Hi @murzagalin!

At the moment, `multiplatform-expressions-evaluator` is distributed via Github Packages. The fact, that Github Packages requires authentication to fetch dependencies makes the setup kinda cumbersome. For example, in a team of multiple developers working on the same project, each developer needs to manually configure the authentication credentials. Also, if you want to use CI & CD it requires additional configuration for the credentials.

That's why I'd highly recommend to upload the library to the [Maven Central Repository](https://maven.apache.org/repository/guide-central-repository-upload.html). This would also make it easier for other developers to use your library, because it drastically simplifies the setup process.

**Comment by murzagalin** [comment]
This is a good idea. I will need to do an investigation first

**Comment by flixlo** [comment]
Hi @murzagalin! Do you have any news on this? My team is still hesitating to use your library - being able to access the library from maven central would be a big deal for us.

**Comment by murzagalin** [comment]
I haven't had time to do this yet. I will work on this next weekend

**Comment by murzagalin** [comment]
@flixlo I published the first release to maven central. Since the version `0.14.0` it is available in maven central

repository:
``` kotlin
    repositories {
        mavenCentral()
    }
```

dependency:
```kotlin
    dependencies {
        implementation("io.github.murzagalin:multiplatform-expressions-evaluator:0.14.1")
    }
```

**NOTE** sonatype repo required to change the groupd id, now it starts with `io` instead of `com` : `io.github.murzagalin`

**Comment by flixlo** [comment]
Yeah, it works 👍 Thank you for your effort!
